import { iphone } from "../assets/images/png/";

const products = [
  {
    id: "1",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "2",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "3",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "4",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "5",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "6",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "7",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "8",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "9",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "10",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "11",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "12",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "13",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "14",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "15",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "16",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "17",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "18",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "19",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "20",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "21",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "22",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "23",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "24",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "25",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "26",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "27",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "28",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "29",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
  {
    id: "30",
    title: "smartphones",
    description: 'Apple iPhone 14 Pro, LTPO Super Retina XDR OLED 6.1"',
    img: iphone,
    old_price: "$1,200.00",
    new_price: "$1.000.00",
  },
];

export default products;
